version: '3'
services:
  web:
    container_name: dev_backend
    build: .
    restart: always
    env_file: dev.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
     - .:/app
    depends_on:
     - db
  db:
    container_name: dev_db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  static_volume:
  postgres_data: