# Generated by Django 3.2.6 on 2021-08-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountdetails',
            name='interest_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
