# Generated by Django 3.2.6 on 2021-08-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_amountdetails_interest_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountdetails',
            name='lender_mobile_number',
            field=models.PositiveBigIntegerField(default=999999999),
        ),
    ]
